/*
 * Copyright 2023 Signal Messenger, LLC
 * SPDX-License-Identifier: AGPL-3.0-only
 */

package org.whispersystems.textsecuregcm.registration;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Nullable;
import org.whispersystems.textsecuregcm.storage.SerializedExpireableJsonDynamoStore;

/**
 * Server-internal stored session object. Primarily used by the
 * {@link org.whispersystems.textsecuregcm.controllers.VerificationController} to manage the steps required to begin
 * verify that a client is the owner of a principal, in order to get a verified session to be provided to the
 * {@link org.whispersystems.textsecuregcm.controllers.RegistrationController}.
 *
 * @param providerId              identifier of the provider used for the principal verification
 *                                this value is requested by the client among the ones configured in Flatline
 * @param clientId                identifier of the client requesting verification to be used in PAR
 *                                this value is randomly generated by Flatline
 * @param state                   value provided by the client to verify authorization responses
 *                                this value is part of the OAuth 2.0 (RFC6749) specification
 * @param redirectUri             location provided by the client to be redirected after authorization
 *                                this value is part of the OAuth 2.0 (RFC6749) specification
 * @param codeChallenge           value provided by the client as the PKCE challenge
 *                                this value part of the Proof Key for Code Exchange (RFC7636) specification
 * @param nonce                   value generated by Flatline to identify tokens that were issued at its request
 *                                this value is part of the OpenID Connect specification
 * @param principal               principal that is allowed to register with this verification session
 * @param createdTimestamp        when this session was created
 * @param updatedTimestamp        when this session was updated
 * @param remoteExpirationSeconds when the remote session expires
 * @see org.whispersystems.textsecuregcm.entities.VerificationSessionResponse
 */
public record VerificationSession(
    String providerId,
    String clientId,
    String state,
    String redirectUri,
    String codeChallenge,
    String nonce,
    @Nullable String principal,
    long createdTimestamp,
    long updatedTimestamp,
    long remoteExpirationSeconds) implements SerializedExpireableJsonDynamoStore.Expireable {

  @Override
  public long getExpirationEpochSeconds() {
    return Instant.ofEpochMilli(updatedTimestamp).plusSeconds(remoteExpirationSeconds).getEpochSecond();
  }

}
