/*
 * Copyright 2013 Signal Messenger, LLC
 * Copyright 2025 Molly Instant Messenger
 * SPDX-License-Identifier: AGPL-3.0-only
 */

package org.whispersystems.textsecuregcm.util;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertThrows;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

class ValidPrincipalTest {

  @ParameterizedTest
  @ValueSource(strings = {
      // Number
      "12345",
      // Name
      "John Doe",
      // Nickname
      "valid.principal",
      // Nickname with allowed special characters
      "#$pecial.nic|<n@me!~",
      // Email address
      "valid.principal@example.com",
      // UUID
      "019a9bd6-c474-7921-9141-6b279426220e",
      // E164
      "+80011111111",
      // 4096-bit RSA public key
      "MIICITANBgkqhkiG9w0BAQEFAAOCAg4AMIICCQKCAgBsTRa+bB5HRELDb/qR9zrepgNHiq81URFQhshPiuDYbTo3IcoYJcwuwL3NcSIjhlh7ZMDZtY8tDK+JjkpgWu7OiySfLP/gJkG61rKJGBDpzmpuqTA4BOh9QEhbbRCJdN8D46Ol/Lw77iNQQs4kMMXYxzalSc3q8egDjGd9FVRHCMq50zZGULmCK9M7H95W75H905UhQSP+1RvW3nA5VOijWy9/nr68FChpcNEq6y1MJ3bQDJrpFRUPVWAVeBztze/P9TQV5I6eRWnDAMu9t5BhQlWA2JKPQXXjlpw8u1z6IQ5g6Xv1wlTrq6NlbESWCbFwuQvjMBdykTQjvsHkfWPgCOfWG0LNIfWnXsEZb8XnRXKNonK1K7HlAS/LS5twf+5SdRu10zrnq/aTEXdsI3W9JZpfUPQ0/azgtpu9OKU2ul3OD7L77GCrZVYICPKKnB92Z5zxeCZD4LzMLXAVMRS1SlvXajGmVR0iph/r0+wKH8R8zvPJVPCydVIQEEYpMjwLDJPbyTKunzOya6bs3vnRNTBI+WvAQ4begQbKjGhEmCKYHTSGkrGTPwwW2IcGntoEx/68Omk01ARpvhlLW8EuRTnV8DusPX7FNLHzwh1My8UBJnnLyeDpObKfmbxlw+b9JBjVeNeebzup8aMJYIgg3doGwmTNAfxhUWcoLpuBHQIDAQAB",
  })
  void requireNormalizedPrincipal(final String principal) {
    assertDoesNotThrow(() -> Util.requireNormalizedPrincipal(principal));
  }

  @Test
  void requireNormalizedPrincipalNull() {
    assertThrows(InvalidPrincipalException.class, () -> Util.requireNormalizedPrincipal(null));
  }

  @ParameterizedTest
  @ValueSource(strings = {
      // Empty
      "",
      // Empty after trimming
      "   ",
      // Too long
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      // With disallowed special characters
      "Nôël Réal-Bjørn", // Extended ASCII
      "⨯", // Unicode 3.2
      "❌", // Unicode 6.0
  })
  void requireNormalizedNumberInvalidNumber(final String number) {
    assertThrows(InvalidPrincipalException.class, () -> Util.requireNormalizedPrincipal(number));
  }

  @ParameterizedTest
  @ValueSource(strings = {
      // Valid principals, but not trimmed
      " valid.principal ",
      " valid.principal",
      "valid.principal ",
  })
  void requireNormalizedPrincipalNonNormalized(final String number) {
    assertThrows(NonNormalizedPrincipalException.class, () -> Util.requireNormalizedPrincipal(number));
  }
}
